[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-login"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-jogador"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-jogos"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-cadastro"
  status = 200
  force = true

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api-estoque"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-pedidos"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-equipes"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-financeiro"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-descontos"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-verifyuser"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-verifyadm"
  status = 200
  force = true

[[redirects]]
  from = "/api/"
  to = "/.netlify/functions/api-resetpassword"
  status = 200
  force = true

[build.environment]
  DISABLE_ESLINT_PLUGIN = "true"
  GENERATE_SOURCEMAP = "false"
  FAST_REFRESH = "false"
  NODE_VERSION = "16.20.2"
  NPM_VERSION = "8.19.4"
